### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by ibell** [ibell/coolprop#22]
For python there is a decent amount of information online, but for other languages there is almost no documentation.

What I would like to see for all languages that we support are example files where we show all the functionality of CoolProp.  These files would be integrated into the documentation build as well, providing a further means of validation.

In practice though, I think we need to limit ourselves to the procedural languages, which in this case would include 
- C++
- ~~Python~~
- ~~MATLAB~~ (rev 06ae407dd54718c5c1cbbc787d968c4a7ae6945d)
- ~~C#~~ (rev fe643960eeff28977d84a374eb804419c1324482)
- ~~Java~~ (rev 622bc73101acd6b5d0580d75a17b709a38f30f2b)
- ~~Octave~~ (rev b7f0d07e1091150a7e20fa736da941a0bd59eca4), issues with REFPROP

Non-procedural wrappers include:
- Labview
- EES
- Modelica

**Comment by Rod-Persky** [comment]
@ibell,

How do you see the examples linking to one another? I can write a few for C++.

Rod

**Comment by ibell** [comment]
I ideally want to demonstrate all the features of CoolProp in each wrapper,
including, (help me fill this out)
1. Single phase inputs
2. Show all the possible two state variable inputs
3. Enable TTSE, use it (bicubic too)
4. Switch unit systems
5. Humid air properties
6. Calling liquids, brines, pure and pseudo-pure fluids
7. Calling REFPROP

**Comment by ibell** [comment]
@Rod-Persky what I imagine is that we just have one file for each language that runs all the same examples.  I started working on this, but never got very far.  It's a maintenance nightmare...

**Comment by ibell** [comment]
Python and MATLAB in rev 9f3106f14daa2d73421738e1c47a731ef5c65174

**Comment by lgpage** [comment]
Shouldn't the python print statements be updated for python 3.x

**Comment by ibell** [comment]
yup, please do - where do you see the old print statements?

**Comment by ibell** [comment]
Ah you mean in the python example I just made, right?  You are right about
that - I'll make the change seeing as how many users are on 3.x

**Comment by lgpage** [comment]
I also get the following error msg:

```
Traceback (most recent call last):
  File "example.py", line 93, in <module>
    CP.set_standard_unit_system(CoolProp.UNIT_SYSTEM_SI)
AttributeError: 'module' object has no attribute 'UNIT_SYSTEM_SI'
```

**Comment by ibell** [comment]
Ah, that's a very recent change I made of bringing all the constants into
the CoolProp main namespace - it was a pain to have to import the constants
module, I could never remember the syntax. I think I have pushed that
change already, so you might just need to recompile the python wrapper

**Comment by lgpage** [comment]
That change on the master branch?
I tried recompiling the python wrapper but still get that error

**Comment by ibell** [comment]
Should be ok now - the dangers of late-night coding! I made the changes
locally rather than in the source folder.  I pushed the fix

**Comment by lgpage** [comment]
I updated and pushed the print statements for python 3.x

**Comment by ibell** [comment]
Nice, thanks for helping with that

**Comment by ibell** [comment]
Fixed in rev 6ad31d6883fa7e8d5b19669298010a8f681526f8
